export default {
  FETCH_FAIL: 'BITFINEX/PUBLIC_FUNDING/FETCH/FAIL',
  FETCH_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/FETCH',
  FETCH_NEXT_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/FETCH/NEXT',
  FETCH_PREV_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/FETCH/PREV',
  JUMP_PUBLIC_FUNDING_PAGE: 'BITFINEX/PUBLIC_FUNDING/PAGE/JUMP',
  REFRESH: 'BITFINEX/PUBLIC_FUNDING/REFRESH',
  SET_SYMBOL: 'BITFINEX/PUBLIC_FUNDING/SYMBOL/SET',
  UPDATE_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/UPDATE',
}
