export default {
  FETCH_FAIL: 'BITFINEX/PUBLIC_FUNDING/FETCH/FAIL',
  FETCH_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/FETCH',
  REFRESH: 'BITFINEX/PUBLIC_FUNDING/REFRESH',
  SET_SYMBOL: 'BITFINEX/PUBLIC_FUNDING/SYMBOL/SET',
  UPDATE_PUBLIC_FUNDING: 'BITFINEX/PUBLIC_FUNDING/UPDATE',
}
