export default {
  FETCH_FAIL: 'BITFINEX/TRADED_VOLUME/FETCH/FAIL',
  FETCH_TRADED_VOLUME: 'BITFINEX/TRADED_VOLUME/FETCH',
  REFRESH: 'BITFINEX/TRADED_VOLUME/REFRESH',
  SET_PARAMS: 'BITFINEX/TRADED_VOLUME/PARAMS/SET',
  SET_PAIRS: 'BITFINEX/TRADED_VOLUME/PAIR/SET',
  ADD_PAIR: 'BITFINEX/TRADED_VOLUME/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/TRADED_VOLUME/PAIR/REMOVE',
  UPDATE_TRADED_VOLUME: 'BITFINEX/TRADED_VOLUME/UPDATE',
}
