export default {
  FETCH_FAIL: 'BITFINEX/WIN_LOSS/FETCH/FAIL',
  FETCH_WIN_LOSS: 'BITFINEX/WIN_LOSS/FETCH',
  REFRESH: 'BITFINEX/WIN_LOSS/REFRESH',
  SET_PARAMS: 'BITFINEX/WIN_LOSS/PARAMS/SET',
  SET_REPORT_TYPE: 'BITFINEX/WIN_LOSS/REPORT_TYPE/SET',
  UPDATE_WIN_LOSS: 'BITFINEX/WIN_LOSS/UPDATE',
}
