export default {
  FETCH_FAIL: 'BITFINEX/ORDER_TRADES/FETCH/FAIL',
  FETCH_ORDER_TRADES: 'BITFINEX/ORDER_TRADES/FETCH',
  REFRESH: 'BITFINEX/ORDER_TRADES/REFRESH',
  SET_PAIR: 'BITFINEX/ORDER_TRADES/PAIR/SET',
  SET_PARAMS: 'BITFINEX/ORDER_TRADES/PARAMS/SET',
  UPDATE_ORDER_TRADES: 'BITFINEX/ORDER_TRADES/UPDATE',
}
