export default {
  FETCH_FAIL: 'BITFINEX/DERIVATIVES/FETCH/FAIL',
  FETCH_DERIVATIVES: 'BITFINEX/DERIVATIVES/FETCH',
  REFRESH: 'BITFINEX/DERIVATIVES/REFRESH',
  UPDATE_DERIVATIVES: 'BITFINEX/DERIVATIVES/UPDATE',
  SET_PAIRS: 'BITFINEX/DERIVATIVES/PAIR/SET',
  ADD_PAIR: 'BITFINEX/DERIVATIVES/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/DERIVATIVES/PAIR/REMOVE',
  CLEAR_PAIRS: 'BITFINEX/DERIVATIVES/PAIR/CLEAR',
}
