export default {
  FETCH_FAIL: 'BITFINEX/SNAPSHOTS/FETCH/FAIL',
  FETCH_SNAPSHOTS: 'BITFINEX/SNAPSHOTS/FETCH',
  REFRESH: 'BITFINEX/SNAPSHOTS/REFRESH',
  SET_TIMESTAMP: 'BITFINEX/SNAPSHOTS/TIMESTAMP/SET',
  UPDATE_SNAPSHOTS: 'BITFINEX/SNAPSHOTS/UPDATE',
}
