export default {
  CANCEL_SNAPSHOTS_GENERATION: 'BITFINEX/SNAPSHOTS/GENERATION/CANCEL',
  FETCH_FAIL: 'BITFINEX/SNAPSHOTS/FETCH/FAIL',
  FETCH_SNAPSHOTS: 'BITFINEX/SNAPSHOTS/FETCH',
  GENERATE_SNAPSHOTS: 'BITFINEX/SNAPSHOTS/GENERATE',
  SET_TIMESTAMP: 'BITFINEX/SNAPSHOTS/TIMESTAMP/SET',
  UPDATE_SNAPSHOTS: 'BITFINEX/SNAPSHOTS/UPDATE',

  SNAPSHOTS_CANCEL: 'FULL_SNAPSHOT_REPORT_INTERRUPTER',
}
