export default {
  CHECK_AUTH: 'BITFINEX/AUTH/CHECK_AUTH',
  CHECK_AUTH_WITH_TOKEN: 'BITFINEX/AUTH/CHECK_AUTH_WITH_TOKEN',
  // SET_API_KEY: 'BITFINEX/AUTH/SET_API_KEY', // moved to state/base
  // SET_API_SECRET: 'BITFINEX/AUTH/SET_API_SECRET',
  SET_AUTH_TOKEN: 'BITFINEX/AUTH/SET_AUTH_TOKEN',
  SHOW_AUTH: 'BITFINEX/AUTH/SHOW_AUTH',
  UPDATE_AUTH_STATUS: 'BITFINEX/AUTH/UPDATE_AUTH_STATUS',
  LOGOUT: 'BITFINEX/AUTH/LOGOUT',
}
