export default {
  CHECK_AUTH: 'BITFINEX/AUTH/CHECK_AUTH',
  SIGN_IN: 'BITFINEX/AUTH/SIGN_IN',
  SIGN_UP: 'BITFINEX/AUTH/SIGN_UP',
  SHOW_AUTH: 'BITFINEX/AUTH/SHOW',
  HIDE_AUTH: 'BITFINEX/AUTH/HIDE',
  UPDATE_AUTH: 'BITFINEX/AUTH/UPDATE_AUTH',
  UPDATE_AUTH_STATUS: 'BITFINEX/AUTH/UPDATE_AUTH_STATUS',
  AUTH_SUCCESS: 'BITFINEX/AUTH/SUCCESS',
  LOGOUT: 'BITFINEX/AUTH/LOGOUT',

  WS_SIGN_IN: 'ws_signIn',
}
