export default {
  FETCH: 'BITFINEX/SUMMARY_BY_ASSET/FETCH',
  FETCH_FAIL: 'BITFINEX/SUMMARY_BY_ASSET/FETCH/FAIL',
  REFRESH: 'BITFINEX/SUMMARY_BY_ASSET/REFRESH',
  UPDATE: 'BITFINEX/SUMMARY_BY_ASSET/UPDATE',
}
