export default {
  FETCH_FAIL: 'BITFINEX/FPAYMENT/FETCH/FAIL',
  FETCH_FPAYMENT: 'BITFINEX/FPAYMENT/FETCH',
  REFRESH: 'BITFINEX/FPAYMENT/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FPAYMENT/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FPAYMENT/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/FPAYMENT/SYMBOL/REMOVE',
  UPDATE_FPAYMENT: 'BITFINEX/FPAYMENT/UPDATE',
}
