export default {
  MODE_ONLINE: 'online',
  MODE_OFFLINE: 'offline',
  MODE_SYNCING: 'syncing',
  SET_SYNC_MODE: 'BITFINEX/SYNC/MODE',
  UPDATE_STATUS: 'BITFINEX/SYNC/UPDATE',
  START_SYNCING: 'BITFINEX/SYNC/START',
  STOP_SYNCING: 'BITFINEX/SYNC/STOP',
  FORCE_OFFLINE: 'BITFINEX/SYNC/OFFLINE',
  SET_PROGRESS: 'BITFINEX/SYNC/PROGRESS/SET',
  SET_PREF: 'BITFINEX/SYNC/PREF/SET',
  SET_PAIR_PREF: 'BITFINEX/SYNC/PREF/SET/PAIR',
  EDIT_PAIR_PREF: 'BITFINEX/SYNC/PREF/EDIT/PAIR',
  SET_SYMBOL_PREF: 'BITFINEX/SYNC/PREF/SET/SYMBOL',
  EDIT_SYMBOL_PREF: 'BITFINEX/SYNC/PREF/EDIT/SYMBOL',

  EDIT_PUBLIC_TRADES_PAIRS_PREF: 'BITFINEX/SYNC/PREF/EDIT/PUBLIC_TRADES_PAIRS_PREF',
  EDIT_PUBLIC_TRADES_SYMBOLS_PREF: 'BITFINEX/SYNC/PREF/EDIT/PUBLIC_TRADES_SYMBOLS_PREF',
  EDIT_TICKERS_HISTORY_PAIRS_PREF: 'BITFINEX/SYNC/PREF/EDIT/TICKERS_HISTORY_PAIRS_PREF',

  WS_PROGRESS_UPDATE: 'ws_emitProgress',
  WS_REQUESTS_REDIRECT: 'ws_emitRedirectingRequestsStatusToApi',
}
