export default {
  MODE_ONLINE: 'online',
  MODE_OFFLINE: 'offline',
  MODE_SYNCING: 'syncing',
  SET_SYNC_MODE: 'BITFINEX/SYNC/MODE',
  UPDATE_STATUS: 'BITFINEX/SYNC/UPDATE',
  START_SYNCING: 'BITFINEX/SYNC/START',
  STOP_SYNCING: 'BITFINEX/SYNC/STOP',
  START_SYNC_NOW: 'BITFINEX/SYNC_NOW/START',
  STOP_SYNC_NOW: 'BITFINEX/SYNC_NOW/STOP',
  FORCE_OFFLINE: 'BITFINEX/SYNC/OFFLINE',
  SET_PROGRESS: 'BITFINEX/SYNC/PROGRESS/SET',
  SET_PREF: 'BITFINEX/SYNC/PREF/SET',

  EDIT_PUBLIC_TRADES_PREF: 'BITFINEX/SYNC/PREF/EDIT/PUBLIC_TRADES',
  EDIT_PUBLIC_FUNDING_PREF: 'BITFINEX/SYNC/PREF/EDIT/PUBLIC_FUNDING',
  EDIT_TICKERS_HISTORY_PREF: 'BITFINEX/SYNC/PREF/EDIT/TICKERS_HISTORY',
  EDIT_CANDLES_PREF: 'BITFINEX/SYNC/PREF/EDIT/CANDLES',
  EDIT_DERIVATIVES_PREF: 'BITFINEX/SYNC/PREF/EDIT/DERIVATIVES',

  EDIT_CONFIG: 'BITFINEX/SYNC/CONFIG/EDIT',

  WS_PROGRESS_UPDATE: 'ws_emitProgress',
  WS_REQUESTS_REDIRECT: 'ws_emitRedirectingRequestsStatusToApi',
}
