export default {
  MODE_ONLINE: 'online',
  MODE_OFFLINE: 'offline',
  MODE_SYNCING: 'syncing',
  SET_SYNC_MODE: 'BITFINEX/SYNC/MODE',
  START_SYNCING: 'BITFINEX/SYNC/START',
  STOP_SYNCING: 'BITFINEX/SYNC/STOP',
  FORCE_OFFLINE: 'BITFINEX/SYNC/OFFLINE',
  SET_PREF:'BITFINEX/SYNC/PREF/SET',
}
