export default {
  FETCH_FAIL: 'BITFINEX/POSITIONS/FETCH/FAIL',
  FETCH_POSITIONS: 'BITFINEX/POSITIONS/FETCH',
  FETCH_NEXT_POSITIONS: 'BITFINEX/POSITIONS/FETCH/NEXT',
  FETCH_PREV_POSITIONS: 'BITFINEX/POSITIONS/FETCH/PREV',
  JUMP_POSITIONS_PAGE: 'BITFINEX/POSITIONS/PAGE/JUMP',
  REFRESH: 'BITFINEX/POSITIONS/REFRESH',
  UPDATE_POSITIONS: 'BITFINEX/POSITIONS/UPDATE',
}
