export default {
  FETCH_FAIL: 'BITFINEX/POSITIONS/FETCH/FAIL',
  FETCH_POSITIONS: 'BITFINEX/POSITIONS/FETCH',
  FETCH_NEXT_POSITIONS: 'BITFINEX/POSITIONS/FETCH/NEXT',
  FETCH_PREV_POSITIONS: 'BITFINEX/POSITIONS/FETCH/PREV',
  JUMP_POSITIONS_PAGE: 'BITFINEX/POSITIONS/PAGE/JUMP',
  REFRESH: 'BITFINEX/POSITIONS/REFRESH',
  SET_PAIRS: 'BITFINEX/POSITIONS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/POSITIONS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/POSITIONS/PAIR/REMOVE',
  UPDATE_POSITIONS: 'BITFINEX/POSITIONS/UPDATE',
}
