export default {
  FETCH_FAIL: 'BITFINEX/POSITIONS/FETCH/FAIL',
  FETCH_POSITIONS: 'BITFINEX/POSITIONS/FETCH',
  REFRESH: 'BITFINEX/POSITIONS/REFRESH',
  SET_PAIRS: 'BITFINEX/POSITIONS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/POSITIONS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/POSITIONS/PAIR/REMOVE',
  CLEAR_PAIRS: 'BITFINEX/POSITIONS/PAIR/CLEAR',
  UPDATE_POSITIONS: 'BITFINEX/POSITIONS/UPDATE',
}
