export default {
  FETCH: 'BITFINEX/LOGINS/FETCH',
  FETCH_FAIL: 'BITFINEX/LOGINS/FETCH/FAIL',
  REFRESH: 'BITFINEX/LOGINS/REFRESH',
  UPDATE: 'BITFINEX/LOGINS/UPDATE',
  SET_PARAMS: 'BITFINEX/LOGINS/PARAMS/SET',
}
