export default {
  CLEAR_STATUS: 'BITFINEX/STATUS/CLEAR',
  UPDATE_STATUS: 'BITFINEX/STATUS/UPDATE',
  UPDATE_SUCCESS_STATUS: 'BITFINEX/STATUS/UPDATE/SUCCESS',
  UPDATE_WARNING_STATUS: 'BITFINEX/STATUS/UPDATE/WARNING',
  UPDATE_ERROR_STATUS: 'BITFINEX/STATUS/UPDATE/ERROR',
}
