export default {
  FETCH_FAIL: 'BITFINEX/WEIGHTED_AVERAGES/FETCH/FAIL',
  FETCH_DERIVATIVES: 'BITFINEX/WEIGHTED_AVERAGES/FETCH',
  REFRESH: 'BITFINEX/WEIGHTED_AVERAGES/REFRESH',
  UPDATE_DERIVATIVES: 'BITFINEX/WEIGHTED_AVERAGES/UPDATE',
  SET_PAIRS: 'BITFINEX/WEIGHTED_AVERAGES/PAIR/SET',
  ADD_PAIR: 'BITFINEX/WEIGHTED_AVERAGES/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/WEIGHTED_AVERAGES/PAIR/REMOVE',
  CLEAR_PAIRS: 'BITFINEX/WEIGHTED_AVERAGES/PAIR/CLEAR',
}
