export default {
  FETCH_FAIL: 'BITFINEX/WEIGHTED_AVERAGES/FETCH/FAIL',
  FETCH_WEIGHTED_AVERAGES: 'BITFINEX/WEIGHTED_AVERAGES/FETCH',
  REFRESH: 'BITFINEX/WEIGHTED_AVERAGES/REFRESH',
  UPDATE_WEIGHTED_AVERAGES: 'BITFINEX/WEIGHTED_AVERAGES/UPDATE',
  SET_PAIR: 'BITFINEX/WEIGHTED_AVERAGES/PAIR/SET',
}
