import queryConstants from 'state/query/constants'

const {
  MENU_LEDGERS,
  MENU_TRADES,
  MENU_ORDERS,
  MENU_MOVEMENTS,
  MENU_POSITIONS,
  MENU_FOFFER,
  MENU_FLOAN,
  MENU_FCREDIT,
  MENU_PUBLIC_TRADES,
  MENU_PUBLIC_FUNDING,
  MENU_TICKERS,
  MENU_DERIVATIVES,
} = queryConstants

const SECTION_COLUMNS = {
  [MENU_LEDGERS]: [
    // { id: 'id', name: 'id' },
    { id: 'description', name: 'description' },
    { id: 'currency', name: 'currency' },
    { id: 'amount', name: 'amount' },
    { id: 'amountUsd', name: 'amountUsd' },
    { id: 'balance', name: 'balance' },
    { id: 'balanceUsd', name: 'balanceUsd' },
    { id: 'mts', name: 'date' },
    { id: 'wallet', name: 'wallet' },
  ],

  [MENU_TRADES]: [
    { id: 'id', name: 'id' },
    { id: 'orderID', name: 'orderid' },
    { id: 'symbol', name: 'pair' },
    { id: 'execAmount', name: 'amount' },
    { id: 'execPrice', name: 'price' },
    // { id: 'orderType', name: 'orderType' },
    // { id: 'orderPrice', name: 'orderPrice' },
    { id: 'fee', name: 'fee' },
    // { id: 'feeCurrency', name: 'feeCurrency' },
    // { id: 'maker', name: 'maker' },
    { id: 'mtsCreate', name: 'time' },
  ],

  [MENU_ORDERS]: [
    { id: 'id', name: 'id' },
    // { id: 'gid', name: 'gid' },
    // { id: 'cid', name: 'cid' },
    { id: 'symbol', name: 'pair' },
    { id: 'type', name: 'type' },
    // { id: 'flags', name: 'flags' },
    // { id: 'amount', name: 'amount' },
    { id: 'amountOrig', name: 'amount' },
    { id: 'amountExecuted', name: 'amount-exe' },
    { id: 'price', name: 'price' },
    { id: 'priceAvg', name: 'avgprice' },
    { id: 'mtsCreate', name: 'create' },
    { id: 'mtsUpdate', name: 'update' },
    { id: 'status', name: 'status' },
    { id: 'priceTrailing', name: 'pricetrail' },
    // { id: 'priceAuxLimit', name: 'priceAuxLimit' },
    // { id: 'notify', name: 'notify' },
    // { id: 'placedId', name: 'placedId' },
    { id: 'typePrev', name: 'typeprev' },
  ],

  [MENU_MOVEMENTS]: [
    { id: 'id', name: 'id' },
    // { id: 'mtsStarted', name: 'mtsStarted' },
    { id: 'mtsUpdated', name: 'date' },
    { id: 'currency', name: 'currency' },
    // { id: 'currencyName', name: 'currencyName' },
    { id: 'status', name: 'status' },
    { id: 'amount', name: 'amount' },
    { id: 'amountUsd', name: 'amountUsd' },
    { id: 'fees', name: 'fees' },
    { id: 'destinationAddress', name: 'destination' },
    { id: 'transactionId', name: 'transactionId' },
  ],

  [MENU_POSITIONS]: [
    { id: 'id', name: 'id' },
    { id: 'symbol', name: 'pair' },
    { id: 'amount', name: 'amount' },
    { id: 'basePrice', name: 'base-price' },
    // { id: 'liquidationPrice', name: 'liquidationPrice' },
    // { id: 'pl', name: 'pl' },
    // { id: 'plPerc', name: 'plPerc' },
    // { id: 'closePrice', name: 'closePrice' },
    { id: 'marginFunding', name: 'swap' },
    { id: 'marginFundingType', name: 'swap-type' },
    { id: 'status', name: 'status' },
    // { id: 'leverage', name: 'leverage' },
    // { id: 'placeholder', name: 'placeholder' },
    // { id: 'mtsCreate', name: 'mtsCreate' },
    { id: 'mtsUpdate', name: 'update' },
  ],

  [MENU_FOFFER]: [
    { id: 'id', name: 'id' },
    { id: 'symbol', name: 'pair' },
    // { id: 'amount', name: 'amount' },
    { id: 'amountOrig', name: 'amount' },
    { id: 'amountExecuted', name: 'amount-exe' },
    { id: 'type', name: 'type' },
    // { id: 'flags', name: 'flags' },
    { id: 'status', name: 'status' },
    { id: 'rate', name: 'rate' },
    // { id: 'rateReal', name: 'rateReal' },
    { id: 'period', name: 'period' },
    // { id: 'notify', name: 'notify' },
    // { id: 'hidden', name: 'hidden' },
    // { id: 'renew', name: 'renew' },
    // { id: 'mtsCreate', name: 'mtsCreate' },
    { id: 'mtsUpdate', name: 'date' },
  ],

  [MENU_FLOAN]: [
    { id: 'id', name: 'id' },
    { id: 'symbol', name: 'symbol' },
    { id: 'side', name: 'side' },
    { id: 'amount', name: 'amount' },
    // { id: 'flags', name: 'flags' },
    { id: 'status', name: 'status' },
    { id: 'rate', name: 'rate' },
    // { id: 'rateReal', name: 'rateReal' },
    { id: 'period', name: 'period' },
    { id: 'mtsOpening', name: 'opening' },
    { id: 'mtsLastPayout', name: 'close' },
    // { id: 'mtsCreate', name: 'mtsCreate' },
    { id: 'mtsUpdate', name: 'date' },
    // { id: 'notify', name: 'notify' },
    // { id: 'hidden', name: 'hidden' },
    // { id: 'renew', name: 'renew' },
    // { id: 'noClose', name: 'noClose' },
  ],

  [MENU_FCREDIT]: [
    { id: 'id', name: 'id' },
    { id: 'symbol', name: 'symbol' },
    { id: 'side', name: 'side' },
    { id: 'amount', name: 'amount' },
    // { id: 'flags', name: 'flags' },
    { id: 'status', name: 'status' },
    { id: 'rate', name: 'rate' },
    // { id: 'rateReal', name: 'rateReal' },
    { id: 'period', name: 'period' },
    { id: 'mtsOpening', name: 'opening' },
    { id: 'mtsLastPayout', name: 'lastpayout' },
    { id: 'positionPair', name: 'positionpair' },
    // { id: 'mtsCreate', name: 'mtsCreate' },
    { id: 'mtsUpdate', name: 'date' },
    // { id: 'notify', name: 'notify' },
    // { id: 'hidden', name: 'hidden' },
    // { id: 'renew', name: 'renew' },
    // { id: 'noClose', name: 'noClose' },
  ],

  [MENU_PUBLIC_TRADES]: [
    { id: 'id', name: 'id' },
    { id: 'mts', name: 'time' },
    // { id: 'rate', name: 'rate' },
    // { id: 'period', name: 'period' },
    // { id: 'type', name: 'type' }, // custom column added on front
    { id: 'price', name: 'price' },
    { id: 'amount', name: 'amount' },
    // { id: 'symbol', name: 'pair' }, // custom column added on front
  ],

  // not currently used
  [MENU_PUBLIC_FUNDING]: [
    { id: 'id', name: 'id' },
    // { id: 'symbol', name: 'symbol' },
    { id: 'mts', name: 'mts' },
    // { id: 'offerID', name: 'offerID' },
    { id: 'amount', name: 'amount' },
    { id: 'rate', name: 'rate' },
    { id: 'period', name: 'period' },
    // { id: 'maker', name: 'maker' },
    // { id: 'currency', name: 'currency' }, // custom column added on front
  ],

  [MENU_TICKERS]: [
    { id: 'pair', name: 'pair' },
    { id: 'bid', name: 'bid' },
    // { id: 'bidPeriod', name: 'bidPeriod' },
    { id: 'ask', name: 'ask' },
    { id: 'mtsUpdate', name: 'time' },
  ],

  [MENU_DERIVATIVES]: [
    { id: 'key', name: 'pair' },
    { id: 'price', name: 'priceDeriv' },
    { id: 'priceSpot', name: 'priceSpot' },
    { id: 'fundBal', name: 'fundBalance' },
    { id: 'fundingAccrued', name: 'fundingAccrued' },
    { id: 'fundingStep', name: 'fundingStep' },
    { id: 'timestamp', name: 'update' },
  ],
}

export default SECTION_COLUMNS
