export default {
  FETCH_FAIL: 'BITFINEX/LEDGERS/FETCH/FAIL',
  FETCH_LEDGERS: 'BITFINEX/LEDGERS/FETCH',
  FETCH_NEXT_LEDGERS: 'BITFINEX/LEDGERS/FETCH/NEXT',
  FETCH_PREV_LEDGERS: 'BITFINEX/LEDGERS/FETCH/PREV',
  JUMP_LEDGERS_PAGE: 'BITFINEX/LEDGERS/PAGE/JUMP',
  REFRESH: 'BITFINEX/LEDGERS/REFRESH',
  SET_SYMBOLS: 'BITFINEX/LEDGERS/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/LEDGERS/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/LEDGERS/SYMBOL/REMOVE',
  UPDATE_LEDGERS: 'BITFINEX/LEDGERS/UPDATE',
}
