export default {
  FETCH_FAIL: 'BITFINEX/LEDGERS/FETCH/FAIL',
  FETCH_LEDGERS: 'BITFINEX/LEDGERS/FETCH',
  REFRESH: 'BITFINEX/LEDGERS/REFRESH',
  SET_SYMBOLS: 'BITFINEX/LEDGERS/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/LEDGERS/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/LEDGERS/SYMBOL/REMOVE',
  UPDATE_LEDGERS: 'BITFINEX/LEDGERS/UPDATE',
}
