export default {
  FETCH_LEDGERS: 'BITFINEX/LEDGERS/FETCH',
  FETCH_NEXT_LEDGERS: 'BITFINEX/LEDGERS/FETCH/NEXT',
  FETCH_PREV_LEDGERS: 'BITFINEX/LEDGERS/FETCH/PREV',
  JUMP_LEDGERS_PAGE: 'BITFINEX/LEDGERS/PAGE/JUMP',
  SET_SYMBOL: 'BITFINEX/LEDGERS/SYMBOL/SET',
  UPDATE_LEDGERS: 'BITFINEX/LEDGERS/UPDATE',
}
