export default {
  FETCH_FAIL: 'BITFINEX/WITHDRAWALS/FETCH/FAIL',
  FETCH_WITHDRAWALS: 'BITFINEX/WITHDRAWALS/FETCH',
  FETCH_NEXT_WITHDRAWALS: 'BITFINEX/WITHDRAWALS/FETCH/NEXT',
  FETCH_PREV_WITHDRAWALS: 'BITFINEX/WITHDRAWALS/FETCH/PREV',
  JUMP_WITHDRAWALS_PAGE: 'BITFINEX/WITHDRAWALS/PAGE/JUMP',
  REFRESH: 'BITFINEX/WITHDRAWALS/REFRESH',
  SET_SYMBOLS: 'BITFINEX/WITHDRAWALS/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/WITHDRAWALS/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/WITHDRAWALS/SYMBOL/REMOVE',
  UPDATE_WITHDRAWALS: 'BITFINEX/WITHDRAWALS/UPDATE',
}
