export default {
  ELECTRON_BACKEND_LOADED: 'BITFINEX/ELECTRON_BACKEND/LOAD',
  TOGGLE_EXPORT_DIALOG: 'BITFINEX/EXPORT_DIALOG/TOGGLE',
  TOGGLE_ERROR_DIALOG: 'BITFINEX/ERROR_DIALOG/TOGGLE',
  TOGGLE_EXPORT_SUCCESS_DIALOG: 'BITFINEX/EXPORT_SUCCESS_DIALOG/TOGGLE',
  TOGGLE_FRAMEWORK_DIALOG: 'BITFINEX/FRAMEWORK_DIALOG/TOGGLE',
  PROCEED_FRAMEWORK_REQUEST: 'BITFINEX/FRAMEWORK_REQUEST/PROCEED',
  TOGGLE_PAGINATION_DIALOG: 'BITFINEX/PAGINATION_DIALOG/TOGGLE',
  TOGGLE_PREFERENCES_DIALOG: 'BITFINEX/PREFERENCES_DIALOG/TOGGLE',
  TOGGLE_TIMEFRAME_DIALOG: 'BITFINEX/TIMEFRAME_DIALOG/TOGGLE',
  PROCEED_PAGINATION_REQUEST: 'BITFINEX/PAGINATION_REQUEST/PROCEED',
  UI_LOADED: 'BITFINEX/UI/LOAD',
  UI_RESIZED: 'BITFINEX/UI/RESIZE',
}
