export default {
  SHOW_CUSTOM_DIALOG: 'BITFINEX/CUSTOM_DIALOG/SHOW',
  TOGGLE_EXPORT_DIALOG: 'BITFINEX/EXPORT_DIALOG/TOGGLE',
  TOGGLE_FRAMEWORK_DIALOG: 'BITFINEX/FRAMEWORK_DIALOG/TOGGLE',
  PROCEED_FRAMEWORK_REQUEST: 'BITFINEX/FRAMEWORK_REQUEST/PROCEED',
  TOGGLE_PAGINATION_DIALOG: 'BITFINEX/PAGINATION_DIALOG/TOGGLE',
  PROCEED_PAGINATION_REQUEST: 'BITFINEX/PAGINATION_REQUEST/PROCEED',
  UI_LOADED: 'BITFINEX/UI/LOAD',
  UI_RESIZED: 'BITFINEX/UI/RESIZE',
}
