export default {
  FETCH_FAIL: 'BITFINEX/WALLETS/FETCH/FAIL',
  FETCH_WALLETS: 'BITFINEX/WALLETS/FETCH',
  REFRESH: 'BITFINEX/WALLETS/REFRESH',
  SET_TIMESTAMP: 'BITFINEX/WALLETS/TIMESTAMP/SET',
  UPDATE_WALLETS: 'BITFINEX/WALLETS/UPDATE',
}
