export default {
  FETCH_FEES_REPORT: 'BITFINEX/FEES_REPORT/FETCH',
  FETCH_FAIL: 'BITFINEX/FEES_REPORT/FETCH/FAIL',
  UPDATE_FEES_REPORT: 'BITFINEX/FEES_REPORT/UPDATE',
  SET_PARAMS: 'BITFINEX/FEES_REPORT/PARAMS/SET',
  SET_REPORT_TYPE: 'BITFINEX/FEES_REPORT/REPORT_TYPE/SET',
  REFRESH: 'BITFINEX/FEES_REPORT/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FEES_REPORT/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FEES_REPORT/SYMBOL/ADD',
  CLEAR_SYMBOLS: 'BITFINEX/FEES_REPORT/SYMBOL/CLEAR',
  REMOVE_SYMBOL: 'BITFINEX/FEES_REPORT/SYMBOL/REMOVE',
}
