export default {
  ADD_PAIR: 'BITFINEX/FEES_REPORT/PAIR/ADD',
  CLEAR_PAIRS: 'BITFINEX/FEES_REPORT/PAIR/CLEAR',
  FETCH_FAIL: 'BITFINEX/FEES_REPORT/FETCH/FAIL',
  FETCH_FEES_REPORT: 'BITFINEX/FEES_REPORT/FETCH',
  REFRESH: 'BITFINEX/FEES_REPORT/REFRESH',
  REMOVE_PAIR: 'BITFINEX/FEES_REPORT/PAIR/REMOVE',
  SET_PARAMS: 'BITFINEX/FEES_REPORT/PARAMS/SET',
  SET_PAIRS: 'BITFINEX/FEES_REPORT/PAIR/SET',
  SET_REPORT_TYPE: 'BITFINEX/FEES_REPORT/REPORT_TYPE/SET',
  UPDATE_FEES_REPORT: 'BITFINEX/FEES_REPORT/UPDATE',
}
