export default {
  FETCH: 'BITFINEX/ACCOUNT_SUMMARY/FETCH',
  FETCH_FAIL: 'BITFINEX/ACCOUNT_SUMMARY/FETCH/FAIL',
  REFRESH: 'BITFINEX/ACCOUNT_SUMMARY/REFRESH',
  UPDATE: 'BITFINEX/ACCOUNT_SUMMARY/UPDATE',
}
