export default {
  ADD: 'BITFINEX/SUB_ACCOUNTS/ADD',
  REMOVE: 'BITFINEX/SUB_ACCOUNTS/REMOVE',
  REMOVE_SUCCESS: 'BITFINEX/SUB_ACCOUNTS/REMOVE/SUCCESS',
  UPDATE: 'BITFINEX/SUB_ACCOUNTS/UPDATE/SUCCESS',
  UPDATE_SUCCESS: 'BITFINEX/SUB_ACCOUNTS/UPDATE/SUCCESS',
}
