export default {
  ADD: 'BITFINEX/SUB_ACCOUNTS/ADD',
  ADD_SUCCESS: 'BITFINEX/SUB_ACCOUNTS/ADD/SUCCESS',
  FETCH: 'BITFINEX/SUB_ACCOUNTS/FETCH',
  REMOVE: 'BITFINEX/SUB_ACCOUNTS/REMOVE',
  REMOVE_SUCCESS: 'BITFINEX/SUB_ACCOUNTS/REMOVE/SUCCESS',
  SET: 'BITFINEX/SUB_ACCOUNTS/SET',
}
