export default {
  FETCH_FAIL: 'BITFINEX/INVOICES/FETCH/FAIL',
  FETCH_INVOICES: 'BITFINEX/INVOICES/FETCH',
  REFRESH: 'BITFINEX/INVOICES/REFRESH',
  SET_SYMBOLS: 'BITFINEX/INVOICES/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/INVOICES/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/INVOICES/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/INVOICES/SYMBOL/CLEAR',
  UPDATE_INVOICES: 'BITFINEX/INVOICES/UPDATE',
}
