export default {
  FETCH_FAIL: 'BITFINEX/INVOICES/FETCH/FAIL',
  FETCH_INVOICES: 'BITFINEX/INVOICESS/FETCH',
  REFRESH: 'BITFINEX/INVOICES/REFRESH',
  SET_PARAMS: 'BITFINEX/INVOICES/PARAMS/SET',
  SET_SYMBOLS: 'BITFINEX/INVOICES/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/INVOICES/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/INVOICES/SYMBOL/REMOVE',
  UPDATE_INVOICES: 'BITFINEX/INVOICES/UPDATE',
}
