export default {
  DATE: 'date',
  CUSTOM: 'custom',
  DEFAULT_RANGE: 'date',
  SET_GO_TO_RANGE: 'BITFINEX/SET/GO_TO_RANGE',
  HANDLE_GO_TO_RANGE: 'BITFINEX/HANDLE/GO_TO_RANGE',
  SET_GO_TO_RANGE_PRESERVE: 'BITFINEX/SET/GO_TO_RANGE_PRESERVE',
}
