export default {
  MENU_MODE_ICON: 'icon',
  MENU_MODE_NORMAL: 'normal',
  MENU_MODE_HOVER: 'hover',
  SET_API_KEY: 'BITFINEX/AUTH/SET_API_KEY',
  SET_API_SECRET: 'BITFINEX/AUTH/SET_API_SECRET',
  SET_AUTH_TOKEN: 'BITFINEX/AUTH/SET_AUTH_TOKEN',
  SET_LANG: 'BITFINEX/LANG/SET',
  SET_MENU_MODE: 'BITFINEX/MENU/SET',
  SET_THEME: 'BITFINEX/THEME/SET',
  SET_TIMEZONE: 'BITFINEX/TIMEZONE/SET',
}
