export default {
  SET_API_KEY: 'BITFINEX/AUTH/SET_API_KEY',
  SET_API_SECRET: 'BITFINEX/AUTH/SET_API_SECRET',
  SET_AUTH_KEY: 'BITFINEX/AUTH/SET_AUTH_KEY',
  SET_LANG: 'BITFINEX/LANG/SET',
  SET_THEME: 'BITFINEX/THEME/SET',
}
