export default {
  FETCH_FAIL: 'BITFINEX/PUBLIC_TRADES/FETCH/FAIL',
  FETCH_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/FETCH',
  FETCH_NEXT_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/FETCH/NEXT',
  FETCH_PREV_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/FETCH/PREV',
  JUMP_PUBLIC_TRADES_PAGE: 'BITFINEX/PUBLIC_TRADES/PAGE/JUMP',
  REFRESH: 'BITFINEX/PUBLIC_TRADES/REFRESH',
  SET_PAIR: 'BITFINEX/PUBLIC_TRADES/PAIR/SET',
  UPDATE_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/UPDATE',
}
