export default {
  FETCH_FAIL: 'BITFINEX/PUBLIC_TRADES/FETCH/FAIL',
  FETCH_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/FETCH',
  REFRESH: 'BITFINEX/PUBLIC_TRADES/REFRESH',
  SET_PAIR: 'BITFINEX/PUBLIC_TRADES/PAIR/SET',
  UPDATE_PUBLIC_TRADES: 'BITFINEX/PUBLIC_TRADES/UPDATE',
}
