export default {
  FETCH_FAIL: 'BITFINEX/PROFITS/FETCH/FAIL',
  FETCH_PROFITS: 'BITFINEX/PROFITS/FETCH',
  REFRESH: 'BITFINEX/PROFITS/REFRESH',
  SET_PARAMS: 'BITFINEX/PROFITS/PARAMS/SET',
  SET_REPORT_TYPE: 'BITFINEX/PROFITS/REPORT_TYPE/SET',
  UPDATE_PROFITS: 'BITFINEX/PROFITS/UPDATE',
}
