export default {
  FETCH_FAIL: 'BITFINEX/TAX_REPORT/FETCH/FAIL',
  FETCH_TAX_REPORT: 'BITFINEX/TAX_REPORT/FETCH',
  FETCH_SNAPSHOT: 'BITFINEX/TAX_REPORT/SNAPSHOT/FETCH',
  FETCH_SNAPSHOT_FAIL: 'BITFINEX/TAX_REPORT/SNAPSHOT/FETCH/FAIL',
  REFRESH: 'BITFINEX/TAX_REPORT/REFRESH',
  SET_PARAMS: 'BITFINEX/TAX_REPORT/PARAMS/SET',
  UPDATE_TAX_REPORT: 'BITFINEX/TAX_REPORT/UPDATE',
  UPDATE_TAX_REPORT_SNAPSHOT: 'BITFINEX/TAX_REPORT/SNAPSHOT/UPDATE',
}
