export default {
  FETCH_FAIL: 'BITFINEX/TAX_REPORT/FETCH/FAIL',
  FETCH_TRANSACTIONS: 'BITFINEX/TAX_REPORT_TRANSACTIONS/FETCH',
  UPDATE_TRANSACTIONS: 'BITFINEX/TAX_REPORT_TRANSACTIONS/UPDATE',
  SET_TRANSACTIONS_STRATEGY: 'BITFINEX/TAX_REPORT_TRANSACTIONS/STRATEGY/SET',
  SET_SHOW_DISCLAIMER: 'BITFINEX/TAX_REPORT_TRANSACTIONS/SHOW_DISCLAIMER/SET',

  STRATEGY_LIFO: 'LIFO',
  STRATEGY_FIFO: 'FIFO',
  WS_TAX_TRANSACTION_REPORT_GENERATION_COMPLETED: 'ws_emitTrxTaxReportGenerationInBackgroundToOne',
}
