export default {
  FETCH_FAIL: 'BITFINEX/TAX_REPORT/FETCH/FAIL',
  FETCH_TRANSACTIONS: 'BITFINEX/TAX_REPORT_TRANSACTIONS/FETCH',
  UPDATE_TRANSACTIONS: 'BITFINEX/TAX_REPORT_TRANSACTIONS/UPDATE',
  SET_TRANSACTIONS_STRATEGY: 'BITFINEX/TAX_REPORT_TRANSACTIONS/STRATEGY/SET',
  SET_SHOW_DISCLAIMER: 'BITFINEX/TAX_REPORT_TRANSACTIONS/SHOW_DISCLAIMER/SET',
  SET_GENERATION_PROGRESS: 'BITFINEX/TAX_REPORT_TRANSACTIONS/GENERATION_PROGRESS/SET',
  CANCEL_TAX_REPORT_GENERATION: 'BITFINEX/TAX_REPORT_TRANSACTIONS/GENERATION/CANCEL',
  SET_SHOW_TAX_REPORT_PRECISION_MODAL: 'BITFINEX/TAX_REPORT_TRANSACTIONS/SHOW_PRECISION_MODAL/SET',

  STRATEGY_LIFO: 'LIFO',
  STRATEGY_FIFO: 'FIFO',
  TAX_REPORT_CANCEL: 'TRX_TAX_REPORT_INTERRUPTER',
  WS_TAX_TRANSACTION_REPORT_GENERATION_PROGRESS: 'ws_emitTrxTaxReportGenerationProgressToOne',
  WS_TAX_TRANSACTION_REPORT_GENERATION_COMPLETED: 'ws_emitTrxTaxReportGenerationInBackgroundToOne',
}
