export default {
  FETCH_FAIL: 'BITFINEX/PAUDIT/FETCH/FAIL',
  FETCH_PAUDIT: 'BITFINEX/PAUDIT/FETCH',
  REFRESH: 'BITFINEX/PAUDIT/REFRESH',
  SET_IDS: 'BITFINEX/PAUDIT/ID/SET',
  ADD_ID: 'BITFINEX/PAUDIT/ID/ADD',
  REMOVE_ID: 'BITFINEX/PAUDIT/ID/REMOVE',
  UPDATE_PAUDIT: 'BITFINEX/PAUDIT/UPDATE',
}
