export default {
  FETCH_FAIL: 'BITFINEX/FCREDIT/FETCH/FAIL',
  FETCH_FCREDIT: 'BITFINEX/FCREDIT/FETCH',
  REFRESH: 'BITFINEX/FCREDIT/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FCREDIT/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FCREDIT/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/FCREDIT/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/FCREDIT/SYMBOL/CLEAR',
  UPDATE_FCREDIT: 'BITFINEX/FCREDIT/UPDATE',
}
