export default {
  FETCH_FAIL: 'BITFINEX/FCREDIT/FETCH/FAIL',
  FETCH_FCREDIT: 'BITFINEX/FCREDIT/FETCH',
  FETCH_NEXT_FCREDIT: 'BITFINEX/FCREDIT/FETCH/NEXT',
  FETCH_PREV_FCREDIT: 'BITFINEX/FCREDIT/FETCH/PREV',
  JUMP_FCREDIT_PAGE: 'BITFINEX/FCREDIT/PAGE/JUMP',
  REFRESH: 'BITFINEX/FCREDIT/REFRESH',
  SET_SYMBOL: 'BITFINEX/FCREDIT/SYMBOL/SET',
  UPDATE_FCREDIT: 'BITFINEX/FCREDIT/UPDATE',
}
