export default {
  FETCH_FAIL: 'BITFINEX/MOVEMENTS/FETCH/FAIL',
  FETCH_MOVEMENTS: 'BITFINEX/MOVEMENTS/FETCH',
  FETCH_NEXT_MOVEMENTS: 'BITFINEX/MOVEMENTS/FETCH/NEXT',
  FETCH_PREV_MOVEMENTS: 'BITFINEX/MOVEMENTS/FETCH/PREV',
  JUMP_MOVEMENTS_PAGE: 'BITFINEX/MOVEMENTS/PAGE/JUMP',
  REFRESH: 'BITFINEX/MOVEMENTS/REFRESH',
  UPDATE_MOVEMENTS: 'BITFINEX/MOVEMENTS/UPDATE',
}
