export default {
  FETCH_FAIL: 'BITFINEX/MOVEMENTS/FETCH/FAIL',
  FETCH_MOVEMENTS: 'BITFINEX/MOVEMENTS/FETCH',
  REFRESH: 'BITFINEX/MOVEMENTS/REFRESH',
  SET_SYMBOLS: 'BITFINEX/MOVEMENTS/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/MOVEMENTS/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/MOVEMENTS/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/LEDGERS/SYMBOL/CLEAR',
  UPDATE_MOVEMENTS: 'BITFINEX/MOVEMENTS/UPDATE',
}
