export default {
  FETCH_FAIL: 'BITFINEX/APOSITIONS/FETCH/FAIL',
  FETCH_APOSITIONS: 'BITFINEX/APOSITIONS/FETCH',
  FETCH_NEXT_APOSITIONS: 'BITFINEX/APOSITIONS/FETCH/NEXT',
  FETCH_PREV_APOSITIONS: 'BITFINEX/APOSITIONS/FETCH/PREV',
  JUMP_APOSITIONS_PAGE: 'BITFINEX/APOSITIONS/PAGE/JUMP',
  REFRESH: 'BITFINEX/APOSITIONS/REFRESH',
  SET_PAIRS: 'BITFINEX/APOSITIONS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/APOSITIONS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/APOSITIONS/PAIR/REMOVE',
  UPDATE_APOSITIONS: 'BITFINEX/APOSITIONS/UPDATE',
}
