export default {
  FETCH_FAIL: 'BITFINEX/APOSITIONS/FETCH/FAIL',
  FETCH_APOSITIONS: 'BITFINEX/APOSITIONS/FETCH',
  REFRESH: 'BITFINEX/APOSITIONS/REFRESH',
  UPDATE_APOSITIONS: 'BITFINEX/APOSITIONS/UPDATE',
}
