export default {
  FETCH_FAIL: 'BITFINEX/FLOAN/FETCH/FAIL',
  FETCH_FLOAN: 'BITFINEX/FLOAN/FETCH',
  FETCH_NEXT_FLOAN: 'BITFINEX/FLOAN/FETCH/NEXT',
  FETCH_PREV_FLOAN: 'BITFINEX/FLOAN/FETCH/PREV',
  JUMP_FLOAN_PAGE: 'BITFINEX/FLOAN/PAGE/JUMP',
  REFRESH: 'BITFINEX/FLOAN/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FLOAN/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FLOAN/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/FLOAN/SYMBOL/REMOVE',
  UPDATE_FLOAN: 'BITFINEX/FLOAN/UPDATE',
}
