export default {
  FETCH_FAIL: 'BITFINEX/FLOAN/FETCH/FAIL',
  FETCH_FLOAN: 'BITFINEX/FLOAN/FETCH',
  REFRESH: 'BITFINEX/FLOAN/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FLOAN/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FLOAN/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/FLOAN/SYMBOL/REMOVE',
  UPDATE_FLOAN: 'BITFINEX/FLOAN/UPDATE',
}
