export default {
  FETCH_FAIL: 'BITFINEX/FLOAN/FETCH/FAIL',
  FETCH_FLOAN: 'BITFINEX/FLOAN/FETCH',
  FETCH_NEXT_FLOAN: 'BITFINEX/FLOAN/FETCH/NEXT',
  FETCH_PREV_FLOAN: 'BITFINEX/FLOAN/FETCH/PREV',
  JUMP_FLOAN_PAGE: 'BITFINEX/FLOAN/PAGE/JUMP',
  REFRESH: 'BITFINEX/FLOAN/REFRESH',
  UPDATE_FLOAN: 'BITFINEX/FLOAN/UPDATE',
}
