export default {
  SET_AUTO_UPDATE_TOAST_TEMPLATE: 'BITFINEX/ELECTRON/AUTO_UPDATE_TOAST/TEMPLATE/SET',
  SET_AUTO_UPDATE_TOAST_PROGRESS: 'BITFINEX/ELECTRON/AUTO_UPDATE_TOAST/PROGRESS/SET',
  CLOSE_AUTO_UPDATE_TOAST: 'BITFINEX/ELECTRON/AUTO_UPDATE_TOAST/CLOSE',
  HIDE_AUTO_UPDATE_TOAST: 'BITFINEX/ELECTRON/AUTO_UPDATE_TOAST/HIDE',
}
