export default {
  GET_ELECTRON_MENU_CONFIG: 'BITFINEX/ELECTRON/MENU_CONFIG/GET',
  SET_ELECTRON_MENU_TITLE: 'BITFINEX/ELECTRON/MENU_TITLE/SET',
  SET_ELECTRON_MENU_TEMPLATE: 'BITFINEX/ELECTRON/MENU_TEMPLATE/SET',
  SET_ELECTRON_MENU_HIDDEN: 'BITFINEX/ELECTRON/MENU_HIDDEN/SET',
}
