import types from './constants'

const testTemplate = [
  {
    label: 'File',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Quit',
        id: 'QUIT_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+Q',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
  {
    label: 'Edit',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Undo',
        id: 'UNDO_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+Z',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Redo',
        id: 'REDO_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+Shift+Z',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Cut',
        id: 'CUT_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+X',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Copy',
        id: 'COPY_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+C',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Paste',
        id: 'PASTE_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+V',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Delete',
        id: 'DELETE_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Select All',
        id: 'SELECT_ALL_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+A',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
  {
    label: 'View',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Reload',
        id: 'RELOAD_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+R',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Force Reload',
        id: 'FORCE_RELOAD_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+Shift+R',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Toggle Developer Tools',
        id: 'TOGGLE_DEV_TOOLS_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+Shift+I',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Actual Size',
        id: 'RESET_ZOOM_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+0',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Zoom In',
        id: 'ZOOM_IN_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl++',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Zoom Out',
        id: 'ZOOM_OUT_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+-',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Toggle Full Screen',
        id: 'TOGGLE_FULL_SCREEN_MENU_ITEM',
        type: 'normal',
        accelerator: 'F11',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
  {
    label: 'Window',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Minimize',
        id: 'MINIMIZE_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+M',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Zoom',
        id: 'ZOOM_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Close',
        id: 'CLOSE_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+W',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
  {
    label: 'Tools',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Data Management',
        type: 'submenu',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: [
          {
            label: 'Export DB',
            id: 'EXPORT_DB_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+E',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
          {
            label: 'Import DB',
            id: 'IMPORT_DB_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+Shift+I',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
          {
            label: 'Restore DB',
            id: 'RESTORE_DB_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+R',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
          {
            label: 'Backup DB',
            id: 'BACKUP_DB_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+B',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
          {
            label: 'Remove DB',
            id: 'REMOVE_DB_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+D',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
          {
            label: 'Clear All Data (except user creds)',
            id: 'CLEAR_ALL_DATA_MENU_ITEM',
            type: 'normal',
            accelerator: 'Ctrl+Alt+C',
            enabled: true,
            visible: true,
            checked: false,
            submenu: null,
          },
        ],
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Change Reports Folder',
        id: 'CHANGE_REPORTS_FOLDER_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Change Sync Frequency',
        id: 'CHANGE_SYNC_FREQUENCY_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
  {
    label: 'Help',
    type: 'submenu',
    accelerator: null,
    enabled: true,
    visible: true,
    checked: false,
    submenu: [
      {
        label: 'Open new GitHub Issue',
        id: 'REPORT_BUG_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+B',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Check for Updates',
        id: 'CHECK_UPDATE_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: false,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Quit and Install updates',
        id: 'INSTALL_UPDATE_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: false,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'User Manual',
        id: 'USER_MANUAL_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+H',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'Changelog',
        id: 'SHOW_CHANGE_LOG_MENU_ITEM',
        type: 'normal',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: '',
        type: 'separator',
        accelerator: null,
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
      {
        label: 'About Bitfinex Report',
        id: 'ABOUT_MENU_ITEM',
        type: 'normal',
        accelerator: 'Ctrl+O',
        enabled: true,
        visible: true,
        checked: false,
        submenu: null,
      },
    ],
  },
]

const initialState = {
  menuTitle: 'Bitfinex Reporting & Performance Tools',
  menuTemplate: testTemplate,
  menuHidden: false,
}

export function electronMenuReducer(state = initialState, action) {
  const { type, payload } = action
  switch (type) {
    case types.SET_ELECTRON_MENU_TITLE:
      return {
        ...state,
        menuTitle: payload,
      }
    case types.SET_ELECTRON_MENU_TEMPLATE:
      return {
        ...state,
        menuTemplate: payload,
      }
    case types.SET_ELECTRON_MENU_HIDDEN:
      return {
        ...state,
        menuHidden: payload,
      }
    default: {
      return state
    }
  }
}

export default electronMenuReducer
