export default {
  TIME_RANGE_LAST_24HOURS: '24hr',
  TIME_RANGE_LAST_2WEEKS: '2w',
  TIME_RANGE_PAST_MONTH: '1m',
  TIME_RANGE_PAST_3MONTH: '3m',
  TIME_RANGE_CUSTOM: 'custom',
  DEFAULT_RANGE: '2w',
  SET_TIME_RANGE: 'BITFINEX/QUERY/SET/TIME_RANGE',
}
