export default {
  FETCH_FAIL: 'BITFINEX/TICKERS/FETCH/FAIL',
  FETCH_TICKERS: 'BITFINEX/TICKERS/FETCH',
  REFRESH: 'BITFINEX/TICKERS/REFRESH',
  SET_PAIRS: 'BITFINEX/TICKERS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/TICKERS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/TICKERS/PAIR/REMOVE',
  CLEAR_PAIRS: 'BITFINEX/TICKERS/PAIR/CLEAR',
  UPDATE_TICKERS: 'BITFINEX/TICKERS/UPDATE',
}
