export default {
  FETCH_FAIL: 'BITFINEX/TICKERS/FETCH/FAIL',
  FETCH_TICKERS: 'BITFINEX/TICKERS/FETCH',
  FETCH_NEXT_TICKERS: 'BITFINEX/TICKERS/FETCH/NEXT',
  FETCH_PREV_TICKERS: 'BITFINEX/TICKERS/FETCH/PREV',
  JUMP_TICKERS_PAGE: 'BITFINEX/TICKERS/PAGE/JUMP',
  REFRESH: 'BITFINEX/TICKERS/REFRESH',
  SET_PAIRS: 'BITFINEX/TICKERS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/TICKERS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/TICKERS/PAIR/REMOVE',
  UPDATE_TICKERS: 'BITFINEX/TICKERS/UPDATE',
}
