export default {
  FETCH_FAIL: 'BITFINEX/FOFFER/FETCH/FAIL',
  FETCH_FOFFER: 'BITFINEX/FOFFER/FETCH',
  REFRESH: 'BITFINEX/FOFFER/REFRESH',
  SET_SYMBOLS: 'BITFINEX/FOFFER/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/FOFFER/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/FOFFER/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/FOFFER/SYMBOL/CLEAR',
  UPDATE_FOFFER: 'BITFINEX/FOFFER/UPDATE',
}
