export default {
  FETCH_FAIL: 'BITFINEX/FOFFER/FETCH/FAIL',
  FETCH_FOFFER: 'BITFINEX/FOFFER/FETCH',
  FETCH_NEXT_FOFFER: 'BITFINEX/FOFFER/FETCH/NEXT',
  FETCH_PREV_FOFFER: 'BITFINEX/FOFFER/FETCH/PREV',
  JUMP_FOFFER_PAGE: 'BITFINEX/FOFFER/PAGE/JUMP',
  REFRESH: 'BITFINEX/FOFFER/REFRESH',
  UPDATE_FOFFER: 'BITFINEX/FOFFER/UPDATE',
}
