export default {
  FETCH_ORDERS: 'BITFINEX/ORDERS/FETCH',
  FETCH_NEXT_ORDERS: 'BITFINEX/ORDERS/FETCH/NEXT',
  FETCH_PREV_ORDERS: 'BITFINEX/ORDERS/FETCH/PREV',
  UPDATE_ORDERS: 'BITFINEX/ORDERS/UPDATE',
}
