export default {
  FETCH_FAIL: 'BITFINEX/ORDERS/FETCH/FAIL',
  FETCH_ORDERS: 'BITFINEX/ORDERS/FETCH',
  FETCH_NEXT_ORDERS: 'BITFINEX/ORDERS/FETCH/NEXT',
  FETCH_PREV_ORDERS: 'BITFINEX/ORDERS/FETCH/PREV',
  JUMP_ORDERS_PAGE: 'BITFINEX/ORDERS/PAGE/JUMP',
  UPDATE_ORDERS: 'BITFINEX/ORDERS/UPDATE',
}
