export default {
  FETCH_FAIL: 'BITFINEX/ORDERS/FETCH/FAIL',
  FETCH_ORDERS: 'BITFINEX/ORDERS/FETCH',
  REFRESH: 'BITFINEX/ORDERS/REFRESH',
  SET_PAIRS: 'BITFINEX/ORDERS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/ORDERS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/ORDERS/PAIR/REMOVE',
  UPDATE_ORDERS: 'BITFINEX/ORDERS/UPDATE',
}
