export default {
  FETCH_FAIL: 'BITFINEX/TRADES/FETCH/FAIL',
  FETCH_TRADES: 'BITFINEX/TRADES/FETCH',
  REFRESH: 'BITFINEX/TRADES/REFRESH',
  SET_PAIRS: 'BITFINEX/TRADES/PAIR/SET',
  ADD_PAIR: 'BITFINEX/TRADES/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/TRADES/PAIR/REMOVE',
  UPDATE_TRADES: 'BITFINEX/TRADES/UPDATE',
}
