export default {
  FETCH_TRADES: 'BITFINEX/TRADES/FETCH',
  FETCH_NEXT_TRADES: 'BITFINEX/ORDERS/FETCH/NEXT',
  FETCH_PREV_TRADES: 'BITFINEX/ORDERS/FETCH/PREV',
  UPDATE_TRADES: 'BITFINEX/TRADES/UPDATE',
}
