export default {
  FETCH_FAIL: 'BITFINEX/DERIVATIVES_STATUS/FETCH/FAIL',
  FETCH_DERIVATIVES_STATUS: 'BITFINEX/DERIVATIVES_STATUS/FETCH',
  REFRESH: 'BITFINEX/DERIVATIVES_STATUS/REFRESH',
  UPDATE_DERIVATIVES_STATUS: 'BITFINEX/DERIVATIVES_STATUS/UPDATE',
  SET_PAIRS: 'BITFINEX/DERIVATIVES_STATUS/PAIR/SET',
  ADD_PAIR: 'BITFINEX/DERIVATIVES_STATUS/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/DERIVATIVES_STATUS/PAIR/REMOVE',
}
