export default {
  FETCH_FAIL: 'BITFINEX/RISK/FETCH/FAIL',
  FETCH_RISK: 'BITFINEX/RISK/FETCH',
  REFRESH: 'BITFINEX/RISK/REFRESH',
  SET_PARAMS: 'BITFINEX/RISK/PARAMS/SET',
  UPDATE_RISK: 'BITFINEX/RISK/UPDATE',
}
