export default {
  FETCH_FAIL: 'BITFINEX/LOAN_REPORT/FETCH/FAIL',
  FETCH_LOAN_REPORT: 'BITFINEX/LOAN_REPORT/FETCH',
  REFRESH: 'BITFINEX/LOAN_REPORT/REFRESH',
  SET_PARAMS: 'BITFINEX/LOAN_REPORT/PARAMS/SET',
  SET_SYMBOLS: 'BITFINEX/LOAN_REPORT/SYMBOLS/SET',
  ADD_SYMBOL: 'BITFINEX/LOAN_REPORT/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/LOAN_REPORT/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/LOAN_REPORT/SYMBOL/CLEAR',
  UPDATE_LOAN_REPORT: 'BITFINEX/LOAN_REPORT/UPDATE',
}
