export default {
  FETCH_FAIL: 'BITFINEX/LOAN_REPORT/FETCH/FAIL',
  FETCH_LOAN_REPORT: 'BITFINEX/LOAN_REPORT/FETCH',
  REFRESH: 'BITFINEX/LOAN_REPORT/REFRESH',
  SET_PARAMS: 'BITFINEX/LOAN_REPORT/PARAMS/SET',
  SET_PAIRS: 'BITFINEX/LOAN_REPORT/PAIR/SET',
  ADD_PAIR: 'BITFINEX/LOAN_REPORT/PAIR/ADD',
  REMOVE_PAIR: 'BITFINEX/LOAN_REPORT/PAIR/REMOVE',
  UPDATE_LOAN_REPORT: 'BITFINEX/LOAN_REPORT/UPDATE',
}
