export default {
  TIME_TYPE_UTC: 'utc',
  TIME_TYPE_LOCALTIME: 'local',
  VALID_QUERY_RANGE: 7776000, // 3 month
  TIME_RANGE_LAST_24HOURS: '24hr',
  TIME_RANGE_YESTERDAY: '1d',
  TIME_RANGE_LAST_2WEEKS: '2w',
  TIME_RANGE_MONTH_TO_DATE: 'm2date',
  TIME_RANGE_PAST_MONTH: '1m',
  TIME_RANGE_PAST_3MONTH: '3m',
  TIME_RANGE_CUSTOM: 'custom',
  SET_TIME_TYPE: 'BITFINEX/QUERY/SET/TIME_TYPE',
  SET_TIME_RANGE: 'BITFINEX/QUERY/SET/TIME_RANGE',
  SET_QUERY_LIMIT: 'BITFINEX/QUERY/SET/LIMIT',
}
