export default {
  FETCH: 'BITFINEX/CANDLES/FETCH',
  FETCH_FAIL: 'BITFINEX/CANDLES/FETCH/FAIL',
  REFRESH: 'BITFINEX/CANDLES/REFRESH',
  SET_PARAMS: 'BITFINEX/CANDLES/PARAMS/SET',
  UPDATE: 'BITFINEX/CANDLES/UPDATE',
  LOADING: 'BITFINEX/CANDLES/CHART/LOADING',
}
