export default {
  FETCH_DATA: 'BITFINEX/SPAYMENT/FETCH',
  FETCH_FAIL: 'BITFINEX/SPAYMENT/FETCH/FAIL',
  REFRESH: 'BITFINEX/SPAYMENT/REFRESH',
  SET_SYMBOLS: 'BITFINEX/SPAYMENT/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/SPAYMENT/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/SPAYMENT/SYMBOL/REMOVE',
  CLEAR_SYMBOLS: 'BITFINEX/SPAYMENT/SYMBOL/CLEAR',
  UPDATE_DATA: 'BITFINEX/SPAYMENT/UPDATE',
}
