export default {
  FETCH_FAIL: 'BITFINEX/AFFILIATES_EARNINGS/FETCH/FAIL',
  FETCH_AFFILIATES_EARNINGS: 'BITFINEX/AFFILIATES_EARNINGS/FETCH',
  REFRESH: 'BITFINEX/AFFILIATES_EARNINGS/REFRESH',
  SET_SYMBOLS: 'BITFINEX/AFFILIATES_EARNINGS/SYMBOL/SET',
  ADD_SYMBOL: 'BITFINEX/AFFILIATES_EARNINGS/SYMBOL/ADD',
  REMOVE_SYMBOL: 'BITFINEX/AFFILIATES_EARNINGS/SYMBOL/REMOVE',
  UPDATE_AFFILIATES_EARNINGS: 'BITFINEX/AFFILIATES_EARNINGS/UPDATE',
}
