export default {
  FETCH_FAIL: 'BITFINEX/BALANCE/FETCH/FAIL',
  FETCH_BALANCE: 'BITFINEX/BALANCE/FETCH',
  REFRESH: 'BITFINEX/BALANCE/REFRESH',
  SET_PARAMS: 'BITFINEX/BALANCE/PARAMS/SET',
  UPDATE_BALANCE: 'BITFINEX/BALANCE/UPDATE',
}
